# spring.application.name=jpa

server:
  port: 8181

spring:
  application:
    name: todo
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Seoul
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB # 1 file maximum size
      max-request-size: 20MB # maximum size for every request

# swagger setting
springdoc:
  swagger-ui:
    path: /myapi.html

jwt:
  secret: yVf6dUeXzHFWcOhu+h40sXkMop3jBB1pXF2Z97KBo06VISECAnUuK+Q7noKhDJVX4gtWo7LiQzb3KfibZAbO9A==

# upload file path
upload:
  path: C:/todo_upload